### ISSUE TITLE
Interpreter can't handle unicode

### ISSUE THREAD

**Issue by Fogapod** [inclement/Pyonic-interpreter#4]
### Problem
App get crashed after entering unicode/emoji symbol to textinput 

### Kivy log
```
[INFO   ] Logger: Record log in /data/user/0/net.inclem.pyonicinterpreter/files/app/.kivy/logs/kivy_17-05-02_5.txt
[INFO   ] Kivy: v1.9.2.dev0, git-6d5494d, 20170409
[INFO   ] Python: v2.7.2 (default, Apr  9 2017, 22:04:42) 
[GCC 5.3 20151204]
[INFO   ] Factory: 194 symbols loaded
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[INFO   ] OSC: using <thread> for socket
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <gl>
[INFO   ] GL: OpenGL version <OpenGL ES 3.0 V@140.0 AU@ (GIT@I741a3d36ca)>
[INFO   ] GL: OpenGL vendor <Qualcomm>
[INFO   ] GL: OpenGL renderer <Adreno (TM) 330>
[INFO   ] GL: OpenGL parsed version: 3, 0
[INFO   ] GL: Texture max size <4096>
[INFO   ] GL: Texture max units <16>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Text: Provider: sdl2
[INFO   ] OSC: listening for Tuio on 127.0.0.1:3001
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[INFO   ] GL: NPOT texture support is available
[ERROR  ] Base: Failed to import "android" module. Could not remove android presplash.
[INFO   ] Base: Leaving application in progress...
[WARNING] stderr: Traceback (most recent call last):
[WARNING] stderr:   File "/home/asandy/devel/pyde/build/bdist.android-armeabi-v7a/pyonic/main.py", line 260, in <module>
[WARNING] stderr:   File "/home/asandy/.local/share/python-for-android/dists/pyonic_python2/private/lib/python2.7/site-packages/kivy/app.py", line 828, in run
[WARNING] stderr:   File "/home/asandy/.local/share/python-for-android/dists/pyonic_python2/private/lib/python2.7/site-packages/kivy/base.py", line 504, in runTouchApp
[WARNING] stderr:   File "/home/asandy/.local/share/python-for-android/dists/pyonic_python2/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 685, in mainloop
[WARNING] stderr:   File "/home/asandy/.local/share/python-for-android/dists/pyonic_python2/private/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 427, in _mainloop
[WARNING] stderr:   File "kivy/core/window/_window_sdl2.pyx", line 426, in kivy.core.window._window_sdl2._WindowSDL2Storage.poll (kivy/core/window/_window_sdl2.c:7651)
[WARNING] stderr: UnicodeEncodeError: 'ascii' codec can't encode character u'\u041b' in position 0: ordinal not in range(128)
```

**Comment by inclement** [comment]
Ah, I thought I'd fixed this. Thanks for the report, I'll look into it.
